# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koda < Formula
  desc "Kong Plugin Development Workbench"
  homepage "https://github.com/raoxiaoyan/koda"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raoxiaoyan/koda/releases/download/v0.1.0/koda_darwin_amd64.tar.gz"
      sha256 "1060c3fd81f111bf64c24deabc5990f19a1b76b115cb5f3f1680c03e09f9f4e9"

      define_method(:install) do
        bin.install "koda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raoxiaoyan/koda/releases/download/v0.1.0/koda_darwin_arm64.tar.gz"
      sha256 "e17d2d07ecee118669a5167c81ae5c83d31be23fe74b2742777a38588d461cea"

      define_method(:install) do
        bin.install "koda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raoxiaoyan/koda/releases/download/v0.1.0/koda_linux_amd64.tar.gz"
      sha256 "c80925e5a91880435d0c8d745ce3048d776c470fd1ded0784c65570ee361956b"
      define_method(:install) do
        bin.install "koda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raoxiaoyan/koda/releases/download/v0.1.0/koda_linux_arm64.tar.gz"
      sha256 "e6552a2fbbf73709e2af6f573164149732a3a1a852593a6abbff553c27a95976"
      define_method(:install) do
        bin.install "koda"
      end
    end
  end

  test do
    system "#{bin}/koda", "version"
  end
end
