# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koda < Formula
  desc "Kong Plugin Development Workbench"
  homepage "https://github.com/raoxiaoyan/koda"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raoxiaoyan/koda/releases/download/v0.1.1/koda_darwin_amd64.tar.gz"
      sha256 "fd7cb3de3eff8141bdb86da1f17b786c2e75bd5db3ddba3b579d9020a1af1ee7"

      define_method(:install) do
        bin.install "koda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raoxiaoyan/koda/releases/download/v0.1.1/koda_darwin_arm64.tar.gz"
      sha256 "f1952f4a7ec51981aba109aa7aee1a906ced15a465d45da58424fcbc0f75014f"

      define_method(:install) do
        bin.install "koda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raoxiaoyan/koda/releases/download/v0.1.1/koda_linux_amd64.tar.gz"
      sha256 "b69dee983b6bcb52f3f0dcd98ff5a4324a78380467c6f92b18b7e4ca844a8863"
      define_method(:install) do
        bin.install "koda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raoxiaoyan/koda/releases/download/v0.1.1/koda_linux_arm64.tar.gz"
      sha256 "d9f6ba5b8e326bdd1ad6a155d22a723613ad83c35281967ddfaedc69090472e5"
      define_method(:install) do
        bin.install "koda"
      end
    end
  end

  test do
    system "#{bin}/koda", "version"
  end
end
